# Generated by Django 4.2.2 on 2023-06-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depart_name', models.CharField(max_length=100)),
                ('Depart_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_first_name', models.CharField(max_length=100)),
                ('Emp_last_name', models.CharField(max_length=100)),
                ('Emp_Salary', models.IntegerField(default=0)),
                ('Emp_bonus', models.IntegerField(default=0)),
                ('Emp_phone', models.IntegerField(default=0)),
                ('Emp_hire_date', models.DateField()),
                ('Emp_Depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
                ('Emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.role')),
            ],
        ),
    ]
